spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    elasticsearch:
      cluster-nodes: 47.114.161.165:9300
      cluster-name:  docker-cluster
  elasticsearch:
    rest:
      uris: http://47.114.161.165:9200
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.macro.mall: debug